#!/usr/bin/env python

from argparse import ArgumentParser, FileType


def parse_args():
    parser = ArgumentParser()
    parser.add_argument("--from-col", "-f", default=0, type=int)
    parser.add_argument("--to-col", "-t", default=1, type=int)
    parser.add_argument("translation", type=FileType("r"))
    parser.add_argument("input", type=FileType("r"))
    parser.add_argument("output", type=FileType("w"))
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    replacements = {
        line.split()[args.from_col]: line.split()[args.to_col]
        for line in args.translation
    }
    for line in args.input:
        for from_str, to_str in replacements.items():
            line = line.replace(from_str, to_str)
        print(line, end="", file=args.output)
